### ISSUE TITLE
Template does not render in Cloudformation designer

### ISSUE THREAD

**Issue by ericmorfamorales** [awslabs/aws-connected-vehicle-solution#1]
When I try to edit this tempate in AWS Cloudformation designer the diagram does not render. Also the conversion to JSON fails. Maybe some identation problem of the YAML file?

It would be nice to take a look at this template in more detail in the designer to see all of its components. Also I want to adapt it to my particular situation and I guess doing it in the designer is less error prone than editing the YAML itself.

**Comment by adeshnangia** [comment]
I am encountering the same issue. Did anyone find a fix?

**Comment by shsenior** [comment]
Can you explain the issues you are encountering with the designer and what the error code is you are seeing? I verified that the V2.0.0 deployment template [deployment/connected-vehicle-platform.yaml] uploaded Apr 17 does display in the CFN designer for the us-east-1 region. As well as, verifying it does convert to JSON.

**Comment by adeshnangia** [comment]
I am getting the following error. The region is US East - Nothern Virginia
Cannot render the template because of an error.: YAMLException: duplicated mapping key at line 2334, column 87: ... function for solution deployment" ^


I am able to create the stack once. However, after deleting the stack, it keeps rolling back. with the following message in the event log:
The following resource(s) failed to create: [AdTrackingTable, VehicleOwnerTable, TelemetricDataBucket, DriverSafetyServiceRole, VehicleTripTable, AnomalyStream, VehicleDtcTable, MarketingPoiTable, VehicleAnomalyTable, ConnectedVehicleUserPool, HealthReportTable, TelemetricsIotActionsRole, TelemetricTripDataBucket, ApiLambdaExecRole, NotificationServiceRole, JitrServiceRole, VehicleServiceRole, DtcServiceRole, DtcTable, TelemetricsDeliveryStreamRole]. . Rollback requested by user.

Best Regards, Adesh Nangia 703-245-9239 (Land-line) 703-945-2850 (Mobile) 

   On Monday, July 9, 2018, 10:45:46 AM EDT, shsenior <notifications@github.com> wrote: 
 
 
Can you explain the issues you are encountering with the designer and what the error code is you are seeing? I verified that the V2.0.0 deployment template [deployment/connected-vehicle-platform.yaml] uploaded Apr 17 does display in the CFN designer for the us-east-1 region. As well as, verifying it does convert to JSON.

**Comment by shsenior** [comment]
I can confirm the duplicate key on line 2334 was removed with the recent commit. Have you pulled the latest assets from this repo?
